site_name: Python FAQ
site_url: https://u-cha.github.io/python-faq/
theme:
  name: material
  logo: img/pythonfaq.png
  icon:
    repo: fontawesome/brands/github
nav:
  - Core Python:
      - Устройство Python: structure_python.md
      - Коллекции: collections.md
      - Generics: generics.md
      - Функции и декораторы: functions.md
      - Итераторы и генераторы: generators.md
      - Контекстные менеджеры: context_managers.md
      - Область видимости: legb.md
  - ООП Python: oop.md
  - Паттерны: patterns.md
  - Многопоточность и асинхронность: async.md
  - Фреймворки: frameworks.md
  - Тестирование: testing.md
  - Очереди сообщений: message_queues.md
  - Инструменты:
      - Системы управления зависимостями: dependency_managers.md
      - Линтеры: linters.md
  - Лайвкодинг: livecoding.md
  - База данных: db.md
  - Изменения в проекте: changelog.md
  #- Шаблон: template.md

plugins:
  - search
  - open-in-new-tab:
      add_icon: True
  - social:
      cards_layout_options:
        logo: img/pythonfaq.png

repo_url: https://github.com/u-cha/python-faq/
repo_name: python-faq gh

extra:
  site_description: сайт-методичка Python-FAQ

